name: Build
on: push

env:
  ANDROID_SDK_TOOLS:  "6514223"
  ANDROID_NDK:        "21.2.6472646"
  ANDROID_CMAKE:      "3.10.2.4988404"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: .github/installAndroidTools.sh

      - name: Build Fontconfig-Android-translator
        run: ./gradlew build -PdisablePreDex

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(./getVersion.sh)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          release_name: "Fontconfig-Android-translator v${{ steps.get_version.outputs.version }} - ${{ github.event.commits[0].message }} - ${{ github.ref }}"
          draft: true
          prerelease: false

      - name: Upload Release aar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib/build/outputs/aar/fontconfig-android-translator.aar
          asset_name: fontconfig-android-translator.aar
          asset_content_type: application/zip

      - name: Generate javadoc
        run: ./gradlew javadocJar

      - name: Upload javadoc.jar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib/build/libs/fontconfig-android-translator-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_name: fontconfig-android-translator-${{steps.get_version.outputs.version}}-javadoc.jar
          asset_content_type: application/zip

      - name: Jar the sources
        run: ./gradlew sourceJar

      - name: Upload sources.jar
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lib/build/libs/fontconfig-android-translator-${{steps.get_version.outputs.version}}-sources.jar
          asset_name: fontconfig-android-translator-${{steps.get_version.outputs.version}}-sources.jar
          asset_content_type: application/zip
